# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 585600b5966479676aad48ab825217fb7b7c3301b24f31ba15389f573e25b78eec84cd2d39888d8142291b4802be16509fbe1a95e93d5ae1a67c99b5b39beb7a

test:
  secret_key_base: 777545e3c94f0f9be9efaadccf5392ec91c149b15daf7dee301e5fd9f7f79854af763697a0f0006499f3bd9839ee1240e8a376c34f90019759d79adda61d3071

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
